import { StyleSheet } from 'react-native';
import { PRIMARYCOLOR } from "../../Constants.js";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
  },
  topview: {
    paddingTop: 60,
    paddingHorizontal: 24,
    backgroundColor: "#121212",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 10,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 25,
  },
  greeting: {
    fontSize: 18,
    color: "#999",
    marginBottom: 8,
  },
  username: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  profilePic: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#2d2d2d",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: PRIMARYCOLOR,
  },
  searchContainer: {
    marginBottom: 30,
    zIndex: 1,
  },
  searchTitle: {
    fontSize: 17,
    color: "#999",
    marginBottom: 12,
    fontWeight: "500",
  },
  searchbar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2d2d2d",
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 56,
    zIndex: 1,
    borderWidth: 1,
    borderColor: "#3d3d3d",
  },
  bottomview: {
    flex: 1,
    backgroundColor: "#121212",
    paddingTop: 20,
  },
  statsCard: {
    backgroundColor: "#2d2d2d",
    marginHorizontal: 24,
    padding: 20,
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4.65,
    elevation: 6,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  statInfo: {
    marginLeft: 12,
  },
  statLabel: {
    fontSize: 14,
    color: "#999",
    fontWeight: "500",
  },
  statValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginTop: 2,
  },
  divider: {
    width: 1,
    backgroundColor: "#3d3d3d",
    marginHorizontal: 15,
    height: '80%',
    alignSelf: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginHorizontal: 24,
    marginTop: 30,
    marginBottom: 16,
  },
  transportList: {
    paddingHorizontal: 24,
    paddingBottom: 100,
  },
  transportCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2d2d2d",
    padding: 16,
    borderRadius: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 4,
  },
  iconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  transportInfo: {
    flex: 1,
  },
  transportName: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 6,
  },
  transportDetail: {
    flexDirection: "row",
    alignItems: "center",
  },
  transportTime: {
    fontSize: 14,
    color: "#999",
    marginLeft: 6,
  },
});